bus:
  server:
    protocol: 'https'
    host: ''
    port: 80
  service:
    name: '@todo'
    version: '@todo'
    ip: '@todo'
    port: '@todo'
    url: '@todo'
    messagesTypes: 
      - { messageType: '@todo', class: 'TodoClass' }