services:
  _defaults:
    autowire: true
    autoconfigure: true
  
  Mbs\MbsBundle\:
    resource: '../../../src/*'
    exclude: '../../../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'
